[package]
name = "jsonschema"
version = "0.1.0"
authors = ["dmitry.dygalo <dmitry.dygalo@kiwi.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.48"
url = "2.1.1"
lazy_static = "1.4.0"
percent-encoding = "2.1.0"
regex = "1.3.4"
rayon = "1.3.0"
base64 = "0.12.0"
chrono = "0.4.10"
reqwest = { version = "0.10.4", features = ["blocking", "json"]}

[dev-dependencies]
criterion = "0.3.1"
draft = {path = "draft"}
jsonschema-valid = "0.4.0"

[[bench]]
name = "jsonschema"
harness = false
