[package]
name = "bench_helpers"
version = "0.1.0"
authors = ["dmitry.dygalo <dadygalo@gmail.com>"]
edition = "2021"
license = "MIT"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
criterion = "0.3"
