name: Python Release

on:
  push:
    tags:
      - python-v*

jobs:

  create_wheels_manylinux:
    runs-on: ubuntu-latest
    name: Create wheels for manylinux
    container: quay.io/pypa/manylinux2010_x86_64
    steps:
      - uses: actions/checkout@v1

      - name: Build and audit wheels
        working-directory: ./python
        run: sh build-wheels.sh

      - run: /opt/python/cp37-cp37m/bin/pip install twine

      - name: Upload package
        working-directory: ./python
        run: /opt/python/cp37-cp37m/bin/twine upload ./dist/* --username=${PYPI_USERNAME} --password=${PYPI_PASSWORD}
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}

  create_source_dist:
    name: Create sdist package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - run: pip install setuptools-rust twine

      - name: Build sdist
        working-directory: ./python
        run: sh build-sdist.sh

      - name: Upload package
        working-directory: ./python
        run: twine upload ./dist/* --username=${PYPI_USERNAME} --password=${PYPI_PASSWORD}
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
